## Documentation: http://docs.travis-ci.com/user/languages/julia/

branches:
  only:
    - master

git:
  depth: 99999999

julia:
  - "1.0" # LTS release
  - "1.2" # current stable release
  - "1.3" # next release
  - nightly

language: julia

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

os:
  - linux

script: julia --code-coverage -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: AutoMerge Integration Tests
      language: julia
      os: linux
      sudo: required
      env:
        - AUTOMERGE_RUN_INTEGRATION_TESTS="true"
        - AUTOMERGE_INTEGRATION_TEST_REPO="bcbi-test/automerge-integration-test-repo"
      julia: "1.2" # current stable release
      before_script:
        - sudo apt-get update
        - sudo apt-get install -y haveged
        - sudo service haveged start
      script: julia --code-coverage -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
      after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
