block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    # "Integration/Julia 1.3/ubuntu-latest/x64",
    "Integration/Julia 1/ubuntu-latest/x64",
    # "Integration/Julia nightly/ubuntu-latest/x64",
    "Unit/Julia 1.3/ubuntu-latest/x64",
    "Unit/Julia 1/ubuntu-latest/x64",
    "Unit/Julia nightly/ubuntu-latest/x64",
    "VersionVigilante",
    # "codecov/patch",
    # "codecov/project",
]

timeout_sec = 7200
